version: 1.{build}-{branch}
branches:
  only:
  - master
skip_non_tags: true

image: Visual Studio 2019
before_build:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")

      {

        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"

      }

      else

      {

        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"

      }

build_script:
  - cmd: >-
      mkdir build-win_x64

      cd build-win_x64

      cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..

      cd ..

      cmake --build build-win_x64 --config Release

artifacts:
- path: build-win_x64\Release
  name: SuperFamicheck-win_x64
