name: Merge

on:
  pull_request:
  push:
    branches: main

jobs:
  unit_tests:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: cd test && make
  build_ubuntu:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
  build_macos:
    needs: unit_tests
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
  build_windows:
    needs: unit_tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
